"""KiCad 9 schematic (.kicad_sch) writer.

Connectivity strategy: every connected pin location gets a short wire stub
and either a power symbol (for rail nets) or a global label. This makes
placement fully deterministic — no wire routing is needed — while producing
a schematic that is electrically complete (verified via kicad-cli ERC and
netlist export).

Only rotation 0 is supported for regular parts; power symbols are attached
with the orientation appropriate for their rail.
"""

from __future__ import annotations

import uuid
from collections import defaultdict

from .design import NC, Design, Part
from .library import Pin, SymbolLibraries
from .sexpr import QStr, Sym, dump

STUB = 3.81  # length of the wire stub from a pin to its label, mm
GRID = 1.27
# Horizontal pins that terminate in a power symbol get a longer run before
# the vertical jog, so the jog column clears neighbouring pins' label anchors
# (connector pin pitch is 2.54 mm and label anchors sit at STUB from the pin).
POWER_RUN = 7.62
POWER_SYMBOLS = {
    "GND": "power:GND",
    "+12V": "power:+12V",
    "+3V3": "power:+3V3",
    "+5V": "power:+5V",
}


def _uid() -> QStr:
    return QStr(str(uuid.uuid4()))


def _font(size: float = 1.27):
    return [Sym("effects"), [Sym("font"), [Sym("size"), size, size]]]


def _hidden_font():
    return [Sym("effects"), [Sym("font"), [Sym("size"), 1.27, 1.27]], [Sym("hide"), Sym("yes")]]


def _prop(name: str, value: str, x: float, y: float, hide: bool = False):
    p = [Sym("property"), QStr(name), QStr(value), [Sym("at"), x, y, 0]]
    p.append(_hidden_font() if hide else _font())
    return p


def _outward(pin: Pin) -> tuple[float, float]:
    """Unit vector pointing away from the symbol body, schematic coords (y down)."""
    return {0: (-1.0, 0.0), 90: (0.0, 1.0), 180: (1.0, 0.0), 270: (0.0, -1.0)}[pin.angle % 360]


def _label_width(net: str) -> float:
    """Rough rendered width of a global label, mm (1.27 font + arrow outline)."""
    return 1.3 * len(net) + 3.5


def _snap(v: float) -> float:
    return round(v / GRID) * GRID


class SchematicWriter:
    def __init__(self, design: Design, libs: SymbolLibraries):
        self.design = design
        self.libs = libs
        self.root_uuid = str(uuid.uuid4())
        self.items: list = []
        self.embedded: dict[str, list] = {}

    # ------------------------------------------------------------------ #

    def build(self) -> str:
        d = self.design
        for part in d.parts:
            self._emit_part(part)
        for note in d.notes:
            self._emit_text(note)

        doc = [
            Sym("kicad_sch"),
            [Sym("version"), Sym("20250114")],
            [Sym("generator"), QStr("pcbflow")],
            [Sym("generator_version"), QStr("9.0")],
            [Sym("uuid"), QStr(self.root_uuid)],
            [Sym("paper"), QStr(d.paper)],
            [
                Sym("title_block"),
                [Sym("title"), QStr(d.title)],
                [Sym("rev"), QStr(d.rev)],
                [Sym("company"), QStr(d.company)],
                [Sym("comment"), 1, QStr("Generated by pcbflow")],
            ],
            [Sym("lib_symbols"), *self.embedded.values()],
            *self.items,
            [Sym("sheet_instances"), [Sym("path"), QStr("/"), [Sym("page"), QStr("1")]]],
            [Sym("embedded_fonts"), Sym("no")],
        ]
        return dump(doc) + "\n"

    # ------------------------------------------------------------------ #

    def _embed(self, lib_id: str):
        if lib_id not in self.embedded:
            self.embedded[lib_id] = self.libs.embeddable(lib_id)

    def _emit_part(self, part: Part):
        if part.rotation != 0:
            raise NotImplementedError("only rotation 0 is supported for parts")
        # Snap to the KiCad connection grid; all library pin offsets are
        # multiples of 1.27 mm, so snapping the origin puts pins on grid.
        part.x = round(part.x / GRID) * GRID
        part.y = round(part.y / GRID) * GRID
        self._embed(part.lib_id)
        pins = self.libs.pins(part.lib_id)
        footprint = part.footprint or self.libs.default_footprint(part.lib_id)

        xs = [p.x for p in pins] or [0]
        ys = [p.y for p in pins] or [0]
        top = part.y - max(ys) - 2.54  # schematic y is down; symbol y is up
        bottom = part.y - min(ys) + 2.54

        layout = self.libs.property_layout(part.lib_id)

        def placed_prop(name: str, value: str):
            if name in layout:
                px, py, angle, justify = layout[name]
                p = [Sym("property"), QStr(name), QStr(value),
                     [Sym("at"), part.x + px, part.y - py, angle]]
                eff = [Sym("effects"), [Sym("font"), [Sym("size"), 1.27, 1.27]]]
                if justify:
                    eff.append([Sym("justify")] + [Sym(j) for j in justify])
                p.append(eff)
                return p
            y = top if name == "Value" else top - 2.54
            return _prop(name, value, part.x, y)

        inst = [
            Sym("symbol"),
            [Sym("lib_id"), QStr(part.lib_id)],
            [Sym("at"), part.x, part.y, 0],
            [Sym("unit"), 1],
            [Sym("exclude_from_sim"), Sym("no")],
            [Sym("in_bom"), Sym("yes")],
            [Sym("on_board"), Sym("yes")],
            [Sym("dnp"), Sym("yes") if part.dnp else Sym("no")],
            [Sym("uuid"), _uid()],
            placed_prop("Reference", part.ref),
            placed_prop("Value", part.value),
            _prop("Footprint", footprint, part.x, bottom, hide=True),
            _prop("Datasheet", "", part.x, bottom, hide=True),
        ]
        for p in pins:
            inst.append([Sym("pin"), QStr(p.number), [Sym("uuid"), _uid()]])
        inst.append(
            [
                Sym("instances"),
                [
                    Sym("project"),
                    QStr(self.design.name),
                    [
                        Sym("path"),
                        QStr("/" + self.root_uuid),
                        [Sym("reference"), QStr(part.ref)],
                        [Sym("unit"), 1],
                    ],
                ],
            ]
        )
        self.items.append(inst)
        self._emit_connections(part, pins)

    # ------------------------------------------------------------------ #

    def _emit_connections(self, part: Part, pins: list[Pin]):
        # Group stacked pins that share one connection point.
        locations: dict[tuple, list[Pin]] = defaultdict(list)
        for p in pins:
            locations[(round(p.x, 3), round(p.y, 3))].append(p)

        taps = {
            t.pin_number: t.symbol
            for t in self.design.power_taps
            if t.part_ref == part.ref
        }

        # For horizontal pins that end in a power symbol, the wire must run
        # past the label text of sibling pins on the same side before it can
        # jog vertically. Also the jog must clear the part body.
        run_by_side = {(-1.0, 0.0): POWER_RUN, (1.0, 0.0): POWER_RUN}
        rails = self.design.rail_nets | set(POWER_SYMBOLS)
        for p in pins:
            net = part.nets.get(p.number)
            if not net or net == NC or net in rails:
                continue
            ox, oy = _outward(p)
            if oy == 0.0:
                key = (ox, oy)
                need = _snap(STUB + _label_width(net)) + GRID
                run_by_side[key] = max(run_by_side[key], need)
        part_bottom = part.y - min((p.y for p in pins), default=0)
        part_top = part.y - max((p.y for p in pins), default=0)

        for (px, py), lpins in locations.items():
            nets = {part.nets[p.number] for p in lpins if p.number in part.nets}
            nets.discard(NC)
            sx, sy = part.x + px, part.y - py
            if not nets:
                explicit_nc = any(part.nets.get(p.number) == NC for p in lpins)
                if explicit_nc or all(p.etype != "power_in" for p in lpins):
                    self.items.append([Sym("no_connect"), [Sym("at"), sx, sy], [Sym("uuid"), _uid()]])
                    continue
                raise ValueError(f"{part.ref} power pin {lpins[0].number} has no net")
            if len(nets) > 1:
                raise ValueError(f"{part.ref}: stacked pins at same point map to {nets}")
            net = nets.pop()

            pin = lpins[0]
            ox, oy = _outward(pin)
            ex, ey = sx + ox * STUB, sy + oy * STUB
            self._wire(sx, sy, ex, ey)

            for p in lpins:
                if p.number in taps:
                    self._power_symbol(taps[p.number], ex, ey, net_name=None)

            side = part.label_side_overrides.get(pin.number)
            run = run_by_side.get((ox, oy), POWER_RUN)
            self._terminate(net, ex, ey, ox, oy, pin, side, run, part_top, part_bottom)

    def _terminate(self, net, ex, ey, ox, oy, pin: Pin, side, run, part_top, part_bottom):
        rails = self.design.rail_nets | set(POWER_SYMBOLS) - {"GND"}
        if net == "GND" and (ox, oy) != (0.0, -1.0):
            if oy == 1.0:  # pointing down: attach directly
                self._power_symbol("power:GND", ex, ey)
            else:  # horizontal: run past sibling labels, drop below the body
                jx = ex + ox * (run - STUB)
                jy = max(ey + 2.54, part_bottom + 2.54)
                self._wire(ex, ey, jx, ey)
                self._wire(jx, ey, jx, jy)
                self._power_symbol("power:GND", jx, jy)
            return
        if net in POWER_SYMBOLS and net in rails and (ox, oy) != (0.0, 1.0):
            if oy == -1.0:  # pointing up: attach directly
                self._power_symbol(POWER_SYMBOLS[net], ex, ey)
            else:  # horizontal: run past sibling labels, rise above the body
                jx = ex + ox * (run - STUB)
                jy = min(ey - 2.54, part_top - 2.54)
                self._wire(ex, ey, jx, ey)
                self._wire(jx, ey, jx, jy)
                self._power_symbol(POWER_SYMBOLS[net], jx, jy)
            return
        self._global_label(net, ex, ey, ox, oy, pin.etype, side)

    # ------------------------------------------------------------------ #

    def _wire(self, x1, y1, x2, y2):
        self.items.append(
            [
                Sym("wire"),
                [Sym("pts"), [Sym("xy"), x1, y1], [Sym("xy"), x2, y2]],
                [Sym("stroke"), [Sym("width"), 0], [Sym("type"), Sym("default")]],
                [Sym("uuid"), _uid()],
            ]
        )

    def _power_symbol(self, lib_id: str, x: float, y: float, net_name=None):
        self._embed(lib_id)
        value = net_name or lib_id.split(":", 1)[1]
        ref_prefix = "#FLG" if "PWR_FLAG" in lib_id else "#PWR"
        n = sum(1 for it in self.items if it[0] == "symbol") + 1
        ref = f"{ref_prefix}0{n:03d}"
        inst = [
            Sym("symbol"),
            [Sym("lib_id"), QStr(lib_id)],
            [Sym("at"), x, y, 0],
            [Sym("unit"), 1],
            [Sym("exclude_from_sim"), Sym("no")],
            [Sym("in_bom"), Sym("yes")],
            [Sym("on_board"), Sym("yes")],
            [Sym("dnp"), Sym("no")],
            [Sym("uuid"), _uid()],
            _prop("Reference", ref, x, y, hide=True),
            _prop("Value", value, x, y + (3.81 if lib_id.endswith("GND") else -3.81)),
            _prop("Footprint", "", x, y, hide=True),
            _prop("Datasheet", "", x, y, hide=True),
            [Sym("pin"), QStr("1"), [Sym("uuid"), _uid()]],
            [
                Sym("instances"),
                [
                    Sym("project"),
                    QStr(self.design.name),
                    [
                        Sym("path"),
                        QStr("/" + self.root_uuid),
                        [Sym("reference"), QStr(ref)],
                        [Sym("unit"), 1],
                    ],
                ],
            ],
        ]
        self.items.append(inst)

    def _global_label(self, net: str, x: float, y: float, ox: float, oy: float, etype: str, side=None):
        # Label anchor sits at the stub end; text extends outward.
        angle = {(1.0, 0.0): 0, (-1.0, 0.0): 180, (0.0, -1.0): 90, (0.0, 1.0): 270}[(ox, oy)]
        shape = {"input": "input", "output": "output", "power_in": "input", "power_out": "output"}.get(
            etype, "bidirectional"
        )
        if side:
            shape = side
        lbl = [
            Sym("global_label"),
            QStr(net),
            [Sym("shape"), Sym(shape)],
            [Sym("at"), x, y, angle],
            [
                Sym("effects"),
                [Sym("font"), [Sym("size"), 1.27, 1.27]],
                [Sym("justify"), Sym("right" if angle == 180 else "left")],
            ],
            [Sym("uuid"), _uid()],
            _prop("Intersheetrefs", "${INTERSHEET_REFS}", x, y, hide=True),
        ]
        self.items.append(lbl)

    def _emit_text(self, note):
        self.items.append(
            [
                Sym("text"),
                QStr(note.text),
                [Sym("exclude_from_sim"), Sym("no")],
                [Sym("at"), note.x, note.y, 0],
                [
                    Sym("effects"),
                    [Sym("font"), [Sym("size"), note.size, note.size]]
                    + ([[Sym("bold"), Sym("yes")]] if note.bold else []),
                    [Sym("justify"), Sym("left"), Sym("bottom")],
                ],
                [Sym("uuid"), _uid()],
            ]
        )


def write_project(design: Design, libs: SymbolLibraries, out_dir):
    """Write .kicad_sch, .kicad_pro and sym-lib-table; return schematic path."""
    from pathlib import Path
    import json
    import os

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    writer = SchematicWriter(design, libs)
    sch_path = out / f"{design.name}.kicad_sch"
    sch_path.write_text(writer.build())

    rows = []
    for lib_id in sorted(writer.embedded):
        lib_name = lib_id.split(":", 1)[0]
        for base in libs.search_paths:
            f = base / f"{lib_name}.kicad_sym"
            if f.exists():
                if str(base).startswith("/usr/share/kicad"):
                    uri = f"${{KICAD9_SYMBOL_DIR}}/{lib_name}.kicad_sym"
                else:
                    rel = os.path.relpath(f, out)
                    uri = f"${{KIPRJMOD}}/{rel}"
                row = f'  (lib (name "{lib_name}")(type "KiCad")(uri "{uri}")(options "")(descr ""))'
                if row not in rows:
                    rows.append(row)
                break
    (out / "sym-lib-table").write_text("(sym_lib_table\n  (version 7)\n" + "\n".join(rows) + "\n)\n")

    pro_path = out / f"{design.name}.kicad_pro"
    pro_path.write_text(
        json.dumps(
            {
                "meta": {"filename": pro_path.name, "version": 3},
                "schematic": {"legacy_lib_dir": "", "legacy_lib_list": []},
            },
            indent=2,
        )
    )
    return sch_path
